"""Unit tests for the ADR-019 auto-refund keeper.

Focus is on the build_keeper factory + the deadline filter logic. The
on-chain tx path is exercised separately via the e2e suite (skipped here
because it needs a running RPC + Postgres).
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

from app.services.auto_refund_keeper import (
    AutoRefundKeeper,
    SELLER_INACTIVITY_INTRA,
    build_keeper,
)


# Test private key — well-known dev key from Hardhat / Foundry. NEVER
# used for anything real. Generated by `cast wallet new --json` style.
DEV_TEST_KEY = (
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
)


def _fake_celo() -> SimpleNamespace:
    return SimpleNamespace(_w3=MagicMock(), _escrow=MagicMock())


def test_build_keeper_returns_none_when_disabled_via_setting() -> None:
    with patch("app.services.auto_refund_keeper.settings") as s:
        s.auto_refund_keeper_enabled = False
        s.relayer_private_key = DEV_TEST_KEY
        keeper = build_keeper(
            celo=_fake_celo(), session_factory=MagicMock()
        )
        assert keeper is None


def test_build_keeper_returns_none_when_relayer_key_empty() -> None:
    with patch("app.services.auto_refund_keeper.settings") as s:
        s.auto_refund_keeper_enabled = True
        s.relayer_private_key = ""
        keeper = build_keeper(
            celo=_fake_celo(), session_factory=MagicMock()
        )
        assert keeper is None


def test_build_keeper_constructs_when_enabled_and_key_present() -> None:
    with patch("app.services.auto_refund_keeper.settings") as s:
        s.auto_refund_keeper_enabled = True
        s.relayer_private_key = DEV_TEST_KEY
        s.auto_refund_keeper_interval_hours = 6.0
        keeper = build_keeper(
            celo=_fake_celo(), session_factory=MagicMock()
        )
        assert isinstance(keeper, AutoRefundKeeper)


def test_keeper_accepts_key_without_0x_prefix() -> None:
    keeper = AutoRefundKeeper(
        celo=_fake_celo(),
        session_factory=MagicMock(),
        relayer_private_key=DEV_TEST_KEY[2:],  # strip "0x"
        interval_hours=1.0,
    )
    # Address derived correctly from the well-known dev key.
    assert keeper._relayer_address == "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"


def test_keeper_clamps_minimum_interval_to_60s() -> None:
    keeper = AutoRefundKeeper(
        celo=_fake_celo(),
        session_factory=MagicMock(),
        relayer_private_key=DEV_TEST_KEY,
        interval_hours=0.001,  # ~3.6 seconds — below the 60s floor
    )
    assert keeper._interval_seconds == 60


def test_inactivity_intra_constant_matches_solidity() -> None:
    # ADR-019. Solidity : `AUTO_REFUND_INACTIVE_INTRA = 7 days`.
    assert SELLER_INACTIVITY_INTRA == timedelta(days=7)


def test_keeper_skips_orders_funded_too_recently() -> None:
    """A Funded order with funded_at < 7d should not be refunded."""
    import asyncio

    keeper = AutoRefundKeeper(
        celo=_fake_celo(),
        session_factory=MagicMock(),
        relayer_private_key=DEV_TEST_KEY,
        interval_hours=1.0,
    )

    now = datetime.now(timezone.utc)
    fresh_order = SimpleNamespace(
        onchain_order_id=42,
        funded_at=now - timedelta(days=3),
        is_cross_border=False,
    )

    sent = []

    async def fake_send(onchain_order_id):
        sent.append(onchain_order_id)

    keeper._send_refund_tx = fake_send  # type: ignore[assignment]
    asyncio.run(keeper._maybe_refund(fresh_order, now))
    assert sent == [], "Should not refund an order funded 3 days ago"


def test_keeper_refunds_orders_past_deadline() -> None:
    """A Funded order with funded_at > 7d should hit _send_refund_tx."""
    import asyncio

    keeper = AutoRefundKeeper(
        celo=_fake_celo(),
        session_factory=MagicMock(),
        relayer_private_key=DEV_TEST_KEY,
        interval_hours=1.0,
    )

    now = datetime.now(timezone.utc)
    stale_order = SimpleNamespace(
        onchain_order_id=99,
        funded_at=now - timedelta(days=10),
        is_cross_border=False,
    )

    sent = []

    async def fake_send(onchain_order_id):
        sent.append(onchain_order_id)

    keeper._send_refund_tx = fake_send  # type: ignore[assignment]
    asyncio.run(keeper._maybe_refund(stale_order, now))
    assert sent == [99]


def test_keeper_respects_cross_border_window() -> None:
    """Cross-border (V2 forward-compat) uses the 14d window."""
    import asyncio

    keeper = AutoRefundKeeper(
        celo=_fake_celo(),
        session_factory=MagicMock(),
        relayer_private_key=DEV_TEST_KEY,
        interval_hours=1.0,
    )

    now = datetime.now(timezone.utc)
    cross_border_order = SimpleNamespace(
        onchain_order_id=7,
        funded_at=now - timedelta(days=10),  # past intra (7d) but not cross (14d)
        is_cross_border=True,
    )

    sent = []

    async def fake_send(onchain_order_id):
        sent.append(onchain_order_id)

    keeper._send_refund_tx = fake_send  # type: ignore[assignment]
    asyncio.run(keeper._maybe_refund(cross_border_order, now))
    assert sent == [], "Cross-border 14d window should not yet have lapsed"
