"""j7_credits_ledger_marketing_images

Revision ID: 73428197ad70
Revises: d5e8b1c4a072
Create Date: 2026-04-26

Sprint J7 Block 6 — adds the two off-chain tables that back the
hybrid credits system (ADR-037):

- marketing_images: one row per generated marketing asset (seller,
  product, template, caption_lang, ipfs_hash, image_url, caption).
- seller_credits_ledger: signed ledger driving the seller's balance.
  Sources are 'purchase' (mirrored from EtaloCredits.CreditsPurchased
  by the indexer), 'welcome_bonus' (10 credits, lazy on first action),
  'monthly_free' (5 credits, lazy once per calendar month), and
  'image_consumption' (-1 credit per generated image, image_id set).

Autogenerated drift on unrelated tables (NOT NULL on users.language,
seller_profiles unique-constraint shape, etc.) was stripped — that
clean-up belongs to a dedicated migration, not this feature commit.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '73428197ad70'
down_revision: Union[str, None] = 'd5e8b1c4a072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'marketing_images',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('seller_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('template', sa.String(length=20), nullable=False),
        sa.Column('caption_lang', sa.String(length=2), nullable=False),
        sa.Column('ipfs_hash', sa.String(length=80), nullable=False),
        sa.Column('image_url', sa.String(length=255), nullable=False),
        sa.Column('caption', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_marketing_images_seller_id', 'marketing_images', ['seller_id'])
    op.create_index('ix_marketing_images_product_id', 'marketing_images', ['product_id'])
    op.create_index('ix_marketing_images_created_at', 'marketing_images', ['created_at'])

    op.create_table(
        'seller_credits_ledger',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('seller_id', sa.UUID(), nullable=False),
        sa.Column('credits_delta', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(length=20), nullable=False),
        sa.Column('image_id', sa.UUID(), nullable=True),
        sa.Column('tx_hash', sa.String(length=80), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source IN ('purchase','welcome_bonus','monthly_free','image_consumption')",
            name='ck_credits_source_valid',
        ),
        sa.ForeignKeyConstraint(['image_id'], ['marketing_images.id']),
        sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tx_hash', 'source', name='uq_credits_tx_source'),
    )
    op.create_index('ix_credits_seller_id', 'seller_credits_ledger', ['seller_id'])
    op.create_index('ix_credits_created_at', 'seller_credits_ledger', ['created_at'])
    op.create_index(
        'ix_credits_seller_source_created',
        'seller_credits_ledger',
        ['seller_id', 'source', 'created_at'],
    )


def downgrade() -> None:
    op.drop_index('ix_credits_seller_source_created', table_name='seller_credits_ledger')
    op.drop_index('ix_credits_created_at', table_name='seller_credits_ledger')
    op.drop_index('ix_credits_seller_id', table_name='seller_credits_ledger')
    op.drop_table('seller_credits_ledger')
    op.drop_index('ix_marketing_images_created_at', table_name='marketing_images')
    op.drop_index('ix_marketing_images_product_id', table_name='marketing_images')
    op.drop_index('ix_marketing_images_seller_id', table_name='marketing_images')
    op.drop_table('marketing_images')
