/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + Celo Sepolia RPC connectivity check.
         *
         *     Returns latest_block from the configured Celo RPC to prove the
         *     backend can reach the chain. If the RPC fails, status flips to
         *     `degraded` and the error is included.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db */
        get: operations["health_db_api_v1_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/redis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Redis */
        get: operations["health_redis_api_v1_health_redis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Nonce */
        post: operations["request_nonce_api_v1_auth_nonce_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Signature */
        post: operations["verify_signature_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user_api_v1_users_me_get"];
        /** Update Current User */
        put: operations["update_current_user_api_v1_users_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{wallet_address}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public Profile */
        get: operations["get_public_profile_api_v1_users__wallet_address__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Seller Profile
         * @description Return the caller's seller profile, or `{profile: null}` if none exists.
         *
         *     The 200+null shape lets the frontend treat "no profile" as a valid
         *     state (redirect to onboarding) without a 404 showing up in the
         *     console as a network error.
         */
        get: operations["get_my_seller_profile_api_v1_sellers_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/handle-available/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Handle Available
         * @description Return whether a shop handle is available for registration.
         *
         *     The check is case-insensitive; handles are stored lowercase. The
         *     endpoint is behind auth so anonymous scripts cannot enumerate taken
         *     handles (small enumeration defense; not a security boundary).
         */
        get: operations["check_handle_available_api_v1_sellers_handle_available__handle__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{seller_address}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Seller Profile V2
         * @description V2 seller profile: stake + reputation + recent orders count.
         *
         *     Reads from indexer-populated DB first; falls back to live RPC for
         *     any field that has no DB row yet (common for never-seen sellers
         *     or shortly after a fresh deploy).
         */
        get: operations["get_seller_profile_v2_api_v1_sellers__seller_address__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/ipfs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload To Ipfs
         * @description Upload an image to IPFS via Pinata.
         *
         *     Falls back to a deterministic dev stub when Pinata credentials are
         *     absent from the backend environment — so local onboarding flows
         *     work end-to-end without depending on the Pinata API during sprint.
         *     The stub is disabled in production (ENFORCE_JWT_AUTH=true refuses
         *     the unauthenticated path upstream anyway).
         */
        post: operations["upload_to_ipfs_api_v1_uploads_ipfs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Onboarding
         * @description Atomic onboarding: create the User (if missing), the SellerProfile,
         *     and the first Product in a single transaction.
         *
         *     Rejects with 409 when the wallet already has a seller profile, or
         *     when the requested handle is taken by another seller.
         */
        post: operations["complete_onboarding_api_v1_onboarding_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/public/{handle}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Product
         * @description Fetch a product by seller handle + slug for the public SSR page.
         *
         *     This endpoint is unauthenticated on purpose — the whole point of
         *     the Next.js web package is a shareable URL any buyer can open
         *     without first being in MiniPay.
         */
        get: operations["get_public_product_api_v1_products_public__handle___slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/public/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Boutique
         * @description Boutique listing for a single seller, used by the public Next.js SSR
         *     page at /{handle}. Lists active products only (filters out drafts,
         *     paused, deleted) ordered by recency, paginated.
         *
         *     Like the single-product endpoint this is unauthenticated — the goal
         *     is a shareable URL any buyer can open without first being in MiniPay.
         */
        get: operations["get_public_boutique_api_v1_products_public__handle__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_v1_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/by-onchain-id/{onchain_order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order By Onchain Id */
        get: operations["get_order_by_onchain_id_api_v1_orders_by_onchain_id__onchain_order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Order Items */
        get: operations["list_order_items_api_v1_orders__order_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Order Groups */
        get: operations["list_order_groups_api_v1_orders__order_id__groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Order Metadata
         * @description Update off-chain order metadata. Caller must be buyer or seller.
         */
        post: operations["update_order_metadata_api_v1_orders__order_id__metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disputes/by-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dispute By Item */
        get: operations["get_dispute_by_item_api_v1_disputes_by_item_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disputes/by-onchain-id/{onchain_dispute_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dispute By Onchain Id */
        get: operations["get_dispute_by_onchain_id_api_v1_disputes_by_onchain_id__onchain_dispute_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disputes/{dispute_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dispute */
        get: operations["get_dispute_api_v1_disputes__dispute_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disputes/{dispute_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Dispute Photo */
        post: operations["add_dispute_photo_api_v1_disputes__dispute_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disputes/{dispute_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Dispute Message */
        post: operations["add_dispute_message_api_v1_disputes__dispute_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/by-onchain-id/{onchain_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item By Onchain Id */
        get: operations["get_item_by_onchain_id_api_v1_items_by_onchain_id__onchain_item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Aggregated dashboard data for the connected seller. All sums default
         *     to 0 on an empty orders table, so the frontend renders empty states
         *     without any backend-side conditional logic.
         */
        get: operations["get_summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description Return the connected wallet's latest notifications. Empty list when
         *     the wallet has no User row yet or no notifications — the frontend
         *     renders "You're all caught up." in that case.
         */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{wallet_address}/sanction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sanction User */
        post: operations["sanction_user_api_v1_admin_users__wallet_address__sanction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Disputes */
        get: operations["list_disputes_api_v1_admin_disputes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/disputes/{order_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Dispute */
        post: operations["resolve_dispute_api_v1_admin_disputes__order_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sitemap/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sitemap Data
         * @description Lightweight sitemap data: all seller handles + active product slugs
         *     with updated_at for lastmod. Consumed by Next.js app/sitemap.ts.
         *
         *     Cache: 1 hour client + CDN side. Re-runs at most once per hour
         *     even under viral share load.
         *
         *     TODO V1.5: filter by SellerProfile.status='active' once status enum
         *     exists. Currently includes every seller with a shop_handle (no NULL
         *     handle exists in V1 — column is NOT NULL).
         */
        get: operations["get_sitemap_data_api_v1_sitemap_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/checkout-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Cart Token
         * @description Validate a cart payload + lock prices/seller info into a 15-minute
         *     HMAC-signed token. The Mini App passes the token at /checkout to
         *     resolve the locked groups for `createOrderWithItems` calls.
         *
         *     Validation per item:
         *       - product must exist
         *       - product.status must be "active"
         *       - product.stock must be ≥ requested qty
         *     Failures aggregate into a single 422 with a `validation_errors` list.
         *
         *     is_cross_border defaults to True (ADR-005, no buyer country in V1).
         *     TODO V1.5: ask buyer country at MiniPay onboarding for accurate
         *     commission tier.
         */
        post: operations["create_cart_token_api_v1_cart_checkout_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/resolve/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Cart Token */
        get: operations["resolve_cart_token_api_v1_cart_resolve__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsSummary */
        AnalyticsSummary: {
            revenue: components["schemas"]["RevenueBlock"];
            /** Active Orders */
            active_orders: number;
            escrow: components["schemas"]["EscrowBlock"];
            reputation: components["schemas"]["app__schemas__analytics__ReputationBlock"];
            /** Top Products */
            top_products: components["schemas"]["TopProductEntry"][];
        };
        /** Body_upload_to_ipfs_api_v1_uploads_ipfs_post */
        Body_upload_to_ipfs_api_v1_uploads_ipfs_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** BoutiquePagination */
        BoutiquePagination: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * BoutiquePublic
         * @description Boutique listing payload for /[handle] SSR page.
         */
        BoutiquePublic: {
            seller: components["schemas"]["ProductPublicSeller"];
            /** Products */
            products: components["schemas"]["ProductPublicListItem"][];
            pagination: components["schemas"]["BoutiquePagination"];
        };
        /** CartItemRequest */
        CartItemRequest: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Qty */
            qty: number;
        };
        /** CartTokenRequest */
        CartTokenRequest: {
            /** Items */
            items: components["schemas"]["CartItemRequest"][];
        };
        /** CartTokenResponse */
        CartTokenResponse: {
            /** Token */
            token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * DisputeLevel
         * @description EtaloDispute LEVEL_* constants — uint8 0..4.
         *
         *     Contract has LEVEL_NONE=0 (uninitialized; openDispute immediately
         *     sets to LEVEL_N1=1). NONE is included here so the indexer can map
         *     `uint8` directly via `list(DisputeLevel)[idx]`. NONE should never
         *     appear in persisted rows.
         * @enum {string}
         */
        DisputeLevel: "None" | "N1_Amicable" | "N2_Mediation" | "N3_Voting" | "Resolved";
        /**
         * DisputeMessageCreate
         * @description Append a message to the dispute conversation.
         */
        DisputeMessageCreate: {
            /** Message */
            message: string;
        };
        /**
         * DisputePhotoCreate
         * @description Append a photo IPFS hash to the dispute's photo list.
         */
        DisputePhotoCreate: {
            /** Ipfs Hash */
            ipfs_hash: string;
            /** Description */
            description?: string | null;
        };
        /** DisputeResponse */
        DisputeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Onchain Dispute Id */
            onchain_dispute_id: number;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * Order Item Id
             * Format: uuid
             */
            order_item_id: string;
            /** Buyer Address */
            buyer_address: string;
            /** Seller Address */
            seller_address: string;
            level: components["schemas"]["DisputeLevel"];
            /** N2 Mediator Address */
            n2_mediator_address: string | null;
            /** Refund Amount Usdt */
            refund_amount_usdt: number;
            /** Slash Amount Usdt */
            slash_amount_usdt: number;
            /** Favor Buyer */
            favor_buyer: boolean | null;
            /** Resolved */
            resolved: boolean;
            /** Reason */
            reason: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * N1 Deadline
             * Format: date-time
             */
            n1_deadline: string;
            /** N2 Deadline */
            n2_deadline: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Buyer Proposal Amount Usdt */
            buyer_proposal_amount_usdt: number | null;
            /** Seller Proposal Amount Usdt */
            seller_proposal_amount_usdt: number | null;
            /** Vote Id */
            vote_id: number | null;
            /** Photo Ipfs Hashes */
            photo_ipfs_hashes: string[] | null;
            /** Conversation */
            conversation: {
                [key: string]: unknown;
            }[] | null;
            /** Refund Amount Human */
            readonly refund_amount_human: string;
            /** Slash Amount Human */
            readonly slash_amount_human: string;
        };
        /** EscrowBlock */
        EscrowBlock: {
            /** In Escrow */
            in_escrow: string;
            /** Released */
            released: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandleAvailabilityResponse */
        HandleAvailabilityResponse: {
            /** Handle */
            handle: string;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** IpfsUploadResponse */
        IpfsUploadResponse: {
            /** Ipfs Hash */
            ipfs_hash: string;
            /** Url */
            url: string;
            /**
             * Is Dev Stub
             * @default false
             */
            is_dev_stub: boolean;
        };
        /**
         * ItemStatus
         * @description EtaloTypes.ItemStatus — 7 states, mirrors contract uint8 0..6.
         * @enum {string}
         */
        ItemStatus: "Pending" | "Shipped" | "Arrived" | "Delivered" | "Released" | "Disputed" | "Refunded";
        /** NonceRequest */
        NonceRequest: {
            /** Wallet Address */
            wallet_address: string;
        };
        /** NonceResponse */
        NonceResponse: {
            /** Nonce */
            nonce: string;
            /** Message */
            message: string;
        };
        /** NotificationRead */
        NotificationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Channel */
            channel: string;
            /** Notification Type */
            notification_type: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Sent */
            sent: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NotificationsListResponse */
        NotificationsListResponse: {
            /** Items */
            items: components["schemas"]["NotificationRead"][];
            /** Total */
            total: number;
        };
        /** OnboardingCompleteProduct */
        OnboardingCompleteProduct: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Price Usdt */
            price_usdt: string;
            /** Stock */
            stock: number;
            /** Status */
            status: string;
        };
        /** OnboardingCompleteRequest */
        OnboardingCompleteRequest: {
            profile: components["schemas"]["OnboardingProfileInput"];
            first_product: components["schemas"]["OnboardingProductInput"];
        };
        /** OnboardingCompleteResponse */
        OnboardingCompleteResponse: {
            profile: components["schemas"]["SellerProfilePublic"];
            first_product: components["schemas"]["OnboardingCompleteProduct"];
        };
        /** OnboardingProductInput */
        OnboardingProductInput: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Price Usdt */
            price_usdt: number | string;
            /** Stock */
            stock: number;
            /** Photo Ipfs Hashes */
            photo_ipfs_hashes: string[];
        };
        /** OnboardingProfileInput */
        OnboardingProfileInput: {
            /** Shop Handle */
            shop_handle: string;
            /** Shop Name */
            shop_name: string;
            /** Country */
            country: string;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Logo Ipfs Hash */
            logo_ipfs_hash?: string | null;
            /** Description */
            description?: string | null;
        };
        /** OrderItemResponse */
        OrderItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Onchain Item Id */
            onchain_item_id: number;
            /** Item Index */
            item_index: number;
            /** Item Price Usdt */
            item_price_usdt: number;
            /** Item Commission Usdt */
            item_commission_usdt: number;
            status: components["schemas"]["ItemStatus"];
            /** Shipment Group Id */
            shipment_group_id: string | null;
            /** Released Amount Usdt */
            released_amount_usdt: number;
            /** Item Price Human */
            readonly item_price_human: string;
        };
        /**
         * OrderListResponse
         * @description Paginated order list.
         */
        OrderListResponse: {
            /** Items */
            items: components["schemas"]["OrderResponse"][];
            /** Count */
            count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * OrderMetadataUpdate
         * @description Off-chain metadata update by buyer or seller. Partial — only
         *     non-None fields are written.
         */
        OrderMetadataUpdate: {
            /** Delivery Address */
            delivery_address?: string | null;
            /** Tracking Number */
            tracking_number?: string | null;
            /** Product Ids */
            product_ids?: string[] | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * OrderResponse
         * @description Full order with embedded items + groups.
         */
        OrderResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Onchain Order Id */
            onchain_order_id: number;
            /** Buyer Address */
            buyer_address: string;
            /** Seller Address */
            seller_address: string;
            /** Total Amount Usdt */
            total_amount_usdt: number;
            /** Total Commission Usdt */
            total_commission_usdt: number;
            /** Is Cross Border */
            is_cross_border: boolean;
            global_status: components["schemas"]["OrderStatus"];
            /** Item Count */
            item_count: number;
            /** Funded At */
            funded_at: string | null;
            /**
             * Created At Chain
             * Format: date-time
             */
            created_at_chain: string;
            /**
             * Created At Db
             * Format: date-time
             */
            created_at_db: string;
            /** Delivery Address */
            delivery_address: string | null;
            /** Tracking Number */
            tracking_number: string | null;
            /** Product Ids */
            product_ids: string[] | null;
            /** Notes */
            notes: string | null;
            /** Items */
            items?: components["schemas"]["OrderItemResponse"][];
            /** Shipment Groups */
            shipment_groups?: components["schemas"]["ShipmentGroupResponse"][];
            /** Total Amount Human */
            readonly total_amount_human: string;
            /** Total Commission Human */
            readonly total_commission_human: string;
        };
        /**
         * OrderStatus
         * @description EtaloTypes.OrderStatus — 9 states, mirrors contract uint8 0..8.
         *
         *     Note: `Disputed` is rarely persisted on-chain in V2 (per Block 7
         *     design, item-level disputes do not flip the order to Disputed
         *     unless every item is in dispute). Indexer should still accept it.
         * @enum {string}
         */
        OrderStatus: "Created" | "Funded" | "PartiallyShipped" | "AllShipped" | "PartiallyDelivered" | "Completed" | "Disputed" | "Refunded" | "Cancelled";
        /**
         * ProductPublic
         * @description Public view of a product, suitable for the SSR product page.
         *     Exposes pre-resolved gateway URLs (IPFS hashes stripped) and the
         *     minimum seller info needed to render the page.
         */
        ProductPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Price Usdt */
            price_usdt: string;
            /** Stock */
            stock: number;
            /** Status */
            status: string;
            /** Image Urls */
            image_urls: string[];
            seller: components["schemas"]["ProductPublicSeller"];
        };
        /**
         * ProductPublicListItem
         * @description Compact product card for the boutique grid. No description, single
         *     primary image — full details live behind /[handle]/[slug].
         */
        ProductPublicListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Price Usdt */
            price_usdt: string;
            /** Stock */
            stock: number;
            /** Primary Image Url */
            primary_image_url?: string | null;
        };
        /** ProductPublicSeller */
        ProductPublicSeller: {
            /** Shop Handle */
            shop_handle: string;
            /** Shop Name */
            shop_name: string;
            /** Logo Url */
            logo_url?: string | null;
            /** Country */
            country?: string | null;
        };
        /** ResolvedCart */
        ResolvedCart: {
            /** Groups */
            groups: components["schemas"]["ResolvedCartSellerGroup"][];
            /** Total Usdt */
            total_usdt: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ResolvedCartItem */
        ResolvedCartItem: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Slug */
            product_slug: string;
            /** Title */
            title: string;
            /** Price Usdt */
            price_usdt: string;
            /** Qty */
            qty: number;
            /** Image Url */
            image_url?: string | null;
        };
        /** ResolvedCartSellerGroup */
        ResolvedCartSellerGroup: {
            /** Seller Handle */
            seller_handle: string;
            /** Seller Shop Name */
            seller_shop_name: string;
            /** Seller Address */
            seller_address: string;
            /** Items */
            items: components["schemas"]["ResolvedCartItem"][];
            /** Subtotal Usdt */
            subtotal_usdt: string;
            /** Is Cross Border */
            is_cross_border: boolean;
        };
        /** RevenueBlock */
        RevenueBlock: {
            /** H24 */
            h24: string;
            /** D7 */
            d7: string;
            /** D30 */
            d30: string;
            /** Timeline 7D */
            timeline_7d: components["schemas"]["TimelinePoint"][];
        };
        /**
         * SellerProfilePublic
         * @description Public view of a seller profile returned to the Mini App.
         *
         *     Never include raw wallet addresses or internal IDs that aren't safe
         *     to render. `logo_ipfs_hash` is kept so the client can build the
         *     gateway URL itself (the IPFS gateway is public).
         */
        SellerProfilePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Shop Handle */
            shop_handle: string;
            /** Shop Name */
            shop_name: string;
            /** Description */
            description?: string | null;
            /** Logo Ipfs Hash */
            logo_ipfs_hash?: string | null;
            /** Banner Ipfs Hash */
            banner_ipfs_hash?: string | null;
            /** Socials */
            socials?: {
                [key: string]: unknown;
            } | null;
            /** Categories */
            categories?: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SellerProfileResponse
         * @description Seller profile = stake + reputation + recent counts.
         *
         *     `source` is "indexer" when both stake and reputation rows came
         *     from the DB, "rpc_fallback" when at least one was loaded
         *     on-demand via CeloService.
         */
        SellerProfileResponse: {
            /** Seller Address */
            seller_address: string;
            stake: components["schemas"]["StakeBlock"];
            reputation: components["schemas"]["app__schemas__seller_v2__ReputationBlock"];
            /** Recent Orders Count */
            recent_orders_count: number;
            /**
             * Source
             * @enum {string}
             */
            source: "indexer" | "rpc_fallback";
        };
        /**
         * SellerStatus
         * @description EtaloReputation.SellerStatus — 3 values for sanction/ban tracking.
         * @enum {string}
         */
        SellerStatus: "Active" | "Suspended" | "Banned";
        /**
         * SellersMeResponse
         * @description Response shape for GET /api/v1/sellers/me.
         *
         *     `profile` is null when the caller has no seller profile yet — the
         *     frontend treats that as "route to onboarding". We intentionally do
         *     not return 404 for this case (see docs/DECISIONS.md).
         */
        SellersMeResponse: {
            profile: components["schemas"]["SellerProfilePublic"] | null;
        };
        /** ShipmentGroupResponse */
        ShipmentGroupResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Onchain Group Id */
            onchain_group_id: number;
            status: components["schemas"]["ShipmentStatus"];
            /** Proof Hash */
            proof_hash: string | null;
            /** Arrival Proof Hash */
            arrival_proof_hash: string | null;
            /** Release Stage */
            release_stage: number;
            /** Shipped At */
            shipped_at: string | null;
            /** Arrived At */
            arrived_at: string | null;
            /** Majority Release At */
            majority_release_at: string | null;
            /** Final Release After */
            final_release_after: string | null;
        };
        /**
         * ShipmentStatus
         * @description EtaloTypes.ShipmentStatus — 4 states, mirrors contract uint8 0..3.
         * @enum {string}
         */
        ShipmentStatus: "Pending" | "Shipped" | "Arrived" | "Delivered";
        /** SitemapData */
        SitemapData: {
            /** Sellers */
            sellers: components["schemas"]["SitemapSeller"][];
            /** Products */
            products: components["schemas"]["SitemapProduct"][];
        };
        /** SitemapProduct */
        SitemapProduct: {
            /** Handle */
            handle: string;
            /** Slug */
            slug: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SitemapSeller */
        SitemapSeller: {
            /** Handle */
            handle: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * StakeBlock
         * @description Per-seller stake state for the seller-profile response.
         */
        StakeBlock: {
            tier: components["schemas"]["StakeTier"];
            /** Amount Usdt */
            amount_usdt: number;
            /** Active Sales */
            active_sales: number;
            /** Freeze Count */
            freeze_count: number;
            /** Amount Human */
            readonly amount_human: string;
        };
        /**
         * StakeTier
         * @description EtaloTypes.StakeTier — 4 values, mirrors contract uint8 0..3.
         *
         *     Contract enum starts at None=0 (sellers without stake). The indexer
         *     maps `uint8` via `list(StakeTier)[idx]`.
         * @enum {string}
         */
        StakeTier: "None" | "Starter" | "Established" | "TopSeller";
        /** TimelinePoint */
        TimelinePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Revenue Usdt */
            revenue_usdt: string;
        };
        /** TopProductEntry */
        TopProductEntry: {
            /** Product Id */
            product_id: string;
            /** Title */
            title: string;
            /** Revenue Usdt */
            revenue_usdt: string;
            /** Image Ipfs Hash */
            image_ipfs_hash?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Wallet Address */
            wallet_address: string;
            /** Signature */
            signature: string;
        };
        /** VerifyResponse */
        VerifyResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ReputationBlock */
        app__schemas__analytics__ReputationBlock: {
            /** Score */
            score: number;
            /** Badge */
            badge: string;
            /** Auto Release Days */
            auto_release_days: number;
        };
        /**
         * ReputationBlock
         * @description Per-seller reputation snapshot.
         */
        app__schemas__seller_v2__ReputationBlock: {
            /** Orders Completed */
            orders_completed: number;
            /** Orders Disputed */
            orders_disputed: number;
            /** Disputes Lost */
            disputes_lost: number;
            /** Total Volume Usdt */
            total_volume_usdt: number;
            /** Score */
            score: number;
            /** Is Top Seller */
            is_top_seller: boolean;
            status: components["schemas"]["SellerStatus"];
            /** Last Sanction At */
            last_sanction_at: string | null;
            /** First Order At */
            first_order_at: string | null;
            /** Total Volume Human */
            readonly total_volume_human: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_db_api_v1_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_redis_api_v1_health_redis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    request_nonce_api_v1_auth_nonce_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NonceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_signature_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_current_user_api_v1_users_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_public_profile_api_v1_users__wallet_address__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_seller_profile_api_v1_sellers_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Wallet-Address"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellersMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_handle_available_api_v1_sellers_handle_available__handle__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Wallet-Address"?: string | null;
            };
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandleAvailabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_seller_profile_v2_api_v1_sellers__seller_address__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seller_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_to_ipfs_api_v1_uploads_ipfs_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Wallet-Address"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_to_ipfs_api_v1_uploads_ipfs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpfsUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_onboarding_api_v1_onboarding_complete_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Wallet-Address"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingCompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_product_api_v1_products_public__handle___slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPublic"];
                };
            };
            /** @description Handle or product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product has been removed */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_boutique_api_v1_products_public__handle__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoutiquePublic"];
                };
            };
            /** @description Shop not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_orders_get: {
        parameters: {
            query?: {
                /** @description Filter by buyer address (any case) */
                buyer?: string | null;
                /** @description Filter by seller address (any case) */
                seller?: string | null;
                status?: components["schemas"]["OrderStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_v1_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_by_onchain_id_api_v1_orders_by_onchain_id__onchain_order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                onchain_order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_order_items_api_v1_orders__order_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_order_groups_api_v1_orders__order_id__groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentGroupResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_metadata_api_v1_orders__order_id__metadata_post: {
        parameters: {
            query?: never;
            header: {
                "X-Etalo-Signature": string;
                "X-Etalo-Timestamp": number;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderMetadataUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dispute_by_item_api_v1_disputes_by_item_get: {
        parameters: {
            query: {
                order_id: string;
                item_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dispute_by_onchain_id_api_v1_disputes_by_onchain_id__onchain_dispute_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                onchain_dispute_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dispute_api_v1_disputes__dispute_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_dispute_photo_api_v1_disputes__dispute_id__photos_post: {
        parameters: {
            query?: never;
            header: {
                "X-Etalo-Signature": string;
                "X-Etalo-Timestamp": number;
            };
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputePhotoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_dispute_message_api_v1_disputes__dispute_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "X-Etalo-Signature": string;
                "X-Etalo-Timestamp": number;
            };
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_by_onchain_id_api_v1_items_by_onchain_id__onchain_item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                onchain_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Wallet-Address"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Wallet-Address"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sanction_user_api_v1_admin_users__wallet_address__sanction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_disputes_api_v1_admin_disputes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    resolve_dispute_api_v1_admin_disputes__order_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sitemap_data_api_v1_sitemap_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapData"];
                };
            };
        };
    };
    create_cart_token_api_v1_cart_checkout_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_cart_token_api_v1_cart_resolve__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedCart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
